CREATE DATABASE SoulTech_DB

CREATE TABLE T_USERS(
    IS_USER INT PRIMARY KEY,
    U_NAME VARCHAR(255) NOT NULL,
    U_EMAIL VARCHAR(255) UNIQUE NOT NULL,
    U_AREA VARCHAR(100)
);

CREATE TABLE T_CATEGORY (
    IS_CATEGORY INT PRIMARY KEY,
    C_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE T_ARTICLES (
    IS_ARTICLE INT PRIMARY KEY,
    A_TITLE VARCHAR(255) NOT NULL,
    A_CONTENT TEXT NOT NULL,
    IS_USER INT,
    A_DATE DATE NOT NULL,
    IS_CATEGORY INT,
    FOREIGN KEY (IS_USER) REFERENCES T_USERS(IS_USER),
    FOREIGN KEY (IS_CATEGORY) REFERENCES T_CATEGORY(IS_CATEGORY)
);

CREATE TABLE T_COMENTS (
    IS_COMENT INT PRIMARY KEY,
    C_TEXT TEXT NOT NULL,
    IS_USER INT,
    C_DATE DATETIME,
    IS_ARTICLE INT,
    FOREIGN KEY (IS_USER) REFERENCES T_USERS(IS_USER),
    FOREIGN KEY (IS_ARTICLE) REFERENCES T_ARTICLES(IS_ARTICLE)
);

CREATE TABLE T_REVISION (
    IS_REVISION INT PRIMARY KEY,
    IS_ARTICLE INT,
    R_STATUS VARCHAR(20) CHECK (R_STATUS IN ('pendente', 'aprovado', 'rejeitado')),
    R_OBSERVATIONS TEXT,
    FOREIGN KEY (IS_ARTICLE) REFERENCES T_ARTICLES(IS_ARTICLE)
);
